# version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/patient_insight
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-2
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models

  airflow:
    image: apache/airflow:2.7.1
    volumes:
      - ./backend/data_pipeline/airflow/dags:/opt/airflow/dags
      - ./backend/scripts:/opt/airflow/scripts
      - ./backend/ml_pipeline:/opt/airflow/ml_pipeline
      - ./logs/airflow:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_HOME=/opt/airflow
    ports:
      - "8080:8080"
    command: bash /opt/airflow/scripts/init-airflow.sh
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - airflow
    volumes:
      - ./backend/data_pipeline/airflow/dags:/opt/airflow/dags
      - ./backend/scripts:/opt/airflow/scripts
      - ./backend/ml_pipeline:/opt/airflow/ml_pipeline
      - ./logs/airflow:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    command: scheduler

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=patient_insight
    ports:
      - "5432:5432"
